CREATE TRIGGER SERIES_METADATA_INHERIT_LIBRARY_READING_DIRECTION
    AFTER INSERT ON SERIES_METADATA
    WHEN NEW.READING_DIRECTION IS NULL
BEGIN
    UPDATE SERIES_METADATA
    SET READING_DIRECTION = (
        SELECT L.DEFAULT_READING_DIRECTION
        FROM SERIES S
        JOIN LIBRARY L ON L.ID = S.LIBRARY_ID
        WHERE S.ID = NEW.SERIES_ID
    )
    WHERE SERIES_ID = NEW.SERIES_ID
      AND EXISTS (
        SELECT 1
        FROM SERIES S
        JOIN LIBRARY L ON L.ID = S.LIBRARY_ID
        WHERE S.ID = NEW.SERIES_ID
          AND L.DEFAULT_READING_DIRECTION IS NOT NULL
      );
END;
